# Generated by Django 4.0.6 on 2022-07-21 13:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='imagenes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagenes')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Imagenes',
            },
        ),
    ]
